### ISSUE TITLE
Feature: User can search for digimon names.

### ISSUE THREAD

**Issue by EuichangPark** [EuichangPark/ajax-project#1]
## ⚙️ Feature

> ##### What capability will users have when this feature is merged?

Users will be able to search the Digimon they want by their names.

## 📐 Functionality

> ##### A description of how the application will work from the perspective of the user.

Users can search Digimon by name. Users will see searched Digimon at a time. Only one Digimon appears at once. 

## 🖼️ Wireframes

> ##### Wireframe screenshot(s) of what the app should look like when it is complete.

![Issue1 Ajax](https://user-images.githubusercontent.com/96793078/156085241-ab4ed52f-150e-43cd-b9dc-7a1b9ffe68c3.PNG)
![Issue1 Ajax mobile](https://user-images.githubusercontent.com/96793078/156085545-86b113b0-c9ef-4506-b851-6a454deff8d6.PNG)

## ✅ Task List

> ##### Commit checklist for tasks needed to complete the feature.

 
- [x] Build initial wireframe.
- [x] Main page's images change every 2 seconds.
- [x] Add Navbar.
- [x] Add "Favorites" button to navbar.
- [x] Add "Search" button to navbar.
- [x] Figure out mobile view to match the wireframe photo above.
- [x] Search bar appears in the middle of the page. 
- [x] Add event listener to the Search button in the navbar for 'click' event.
- [x] Search bar has a placeholder. (Search by name)
- [x] Get Search Icon from "Font awesome".
- [x] Add an event listener for the search icon.
- [x] If the value of the input area matches one of the property values of data, it appears on the screen.
- [x] If searched Digimon doesn't exist, it shows "Searched Digimon doesn’t exist." message.
- [x] One searched Digimon appears on the screen.
- [x] Make sure that click targets are either `<a>` or `<button>` elements.
- [x] Make sure that all click targets show a `cursor: pointer` when hovered with the mouse.
- **Clean Up**
  - [x] Remove all buttons and placeholders that do not serve the functionality of the feature.
  - [x] Remove all console logs.
  - [x] Remove all commented out code.
  - [x] Remove all CSS properties that have no effect.
  - [x] Check all code for proper formatting and indentation.
  - [x] Confirm that there are no errors in the console while using the application.
  - [x] Confirm that all previous functionality still works without errors.
  - [x] Confirm that the user interface looks natural on both mobile and desktop screens.
  - [x] Create GIFs of the feature being used on both mobile and desktop screen sizes for inclusion in Pull Request.
