### ISSUE TITLE
User can search by level

### ISSUE THREAD

**Issue by EuichangPark** [EuichangPark/ajax-project#2]
## ⚙️ Feature

> ##### What capability will users have when this feature is merged?

Users can view all Digimon with the same level.
## 📐 Functionality

> ##### A description of how the application will work from the perspective of the user.

Users can view all Digimon with the same level for the "click" and "like" features.
## 🖼️ Wireframes

> ##### Wireframe screenshot(s) of what the app should look like when it is complete.

![fagmaf2mobile](https://user-images.githubusercontent.com/96793078/156820303-0d8ae549-1725-4bf1-85c6-10c205626221.PNG)
![figmaf2](https://user-images.githubusercontent.com/96793078/156820304-6a899bd9-4e2e-4168-9c48-1c9523e3a6aa.PNG)

## ✅ Task List

> ##### Commit checklist for tasks needed to complete the feature.

- [x] ... 
- [x] Make sure when the search is clicked from the navbar, it gives the option to click level.
- [x] When the level is clicked, all the Digimon with the same level appears.
- [x] Add add button when Digimon is searched.
- [x] Make sure that click targets are either `<a>` or `<button>` elements.
- [x] Make sure that all click targets show a `cursor: pointer` when hovered with the mouse.
- **Clean Up**
  - [x] Remove all buttons and placeholders that do not serve the functionality of the feature.
  - [x] Remove all console logs.
  - [x] Remove all commented out code.
  - [x] Remove all CSS properties that have no effect.
  - [x] Check all code for proper formatting and indentation.
  - [x] Confirm that there are no errors in the console while using the application.
  - [x] Confirm that all previous functionality still works without errors.
  - [x] Confirm that the user interface looks natural on both mobile and desktop screens.
  - [x] Create GIFs of the feature being used on both mobile and desktop screen sizes for inclusion in Pull Request.
